import Head from 'next/head'

export default function Home() {
    return (
        <div className={`min-h-[100vh] min-w-[100vw] bg-black flex text-white items-center justify-center overflow-x-hidden overflow-y-scroll whitespace-normal`}>

            <Head>

                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                
            </Head>

            <section className='max-w-[80vw] overflow-hidden'>

                <p className='text-[#C6C100]'>&#123;</p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Identité&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Prénom&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Lucas&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Sexe&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Masculin&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Nationalité&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Française&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Description&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Entreprenant, travailleur, de solides capacités d&apos;apprentissage&quot;</span><span>,</span></p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Contact&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;E-mail&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='mailto:lucasbriandbr@proton.me'>lucasbrianbdr@proton.me</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Téléphone&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='tel:+33750068971'>+33 7 50 06 89 71</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Github&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://github.com/lucasbriandbr'>https://github.com/lucasbriandbr</a>&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Diplômes&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Baccalauréat&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Scientifque, Physique-Chimie, Mathématiques, Sciences de l&apos;Ingénieur; option Mathématiques Expertes&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;BTS&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;SIO (Service Informatique aux Organisations)&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Expériences&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Cruisetech SARL&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Développeur Apprenti chez Cruiseline SAM Monaco, première société de vente de croisières en ligne pour une durée de deux ans&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Mc Donald's&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Equipier polyvalent pour un an sur Nice&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Travaux&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Bootook&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://www.bootook.com/'>https://www.bootook.com/</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Portfolio&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://www.lucasbriand.me/'>https://www.lucasbriand.me/</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Andromeda Mechs&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://github.com/lucasbriandbr/P2E-SOL/tree/main/webapp'>https://www.andromedamechs.com/</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Cruses&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://github.com/lucasbriandbr/Cruses'>https://www.cruses.com/</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;GPT-3 Telegram Bot&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://github.com/lucasbriandbr/OpenAI-Telegram-Bot'>https://github.com/lucasbriandbr/OpenAI-Telegram-Bot</a>&quot;</span><span>,</span></p>

                        {/* <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;GPT-3 Telegram Bot&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://github.com/lucasbriandbr/OpenAI-Telegram-Bot'>https://github.com/lucasbriandbr/OpenAI-Telegram-Bot</a>&quot;</span><span>,</span></p> */}

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>

                <p className='flex gap-4 text-[#C6C100]'><span>&#125;</span></p>

            </section>

        </div>
    )
}
