import Head from 'next/head'

export default function Home() {
    return (
        <div className={`min-h-[100vh] min-w-[100vw] bg-black flex text-white items-center justify-center overflow-hidden`}>

            <Head>

                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                
            </Head>

            <section>

                <p className='text-[#C6C100]'>&#123;</p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Identité&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Prénom&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Lucas&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Sexe&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Masculin&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Nationalité&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Française&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Description&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;Entreprenant, travailleur, de solides capacités d&apos;apprentissage&quot;</span><span>,</span></p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Contact&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;E-mail&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='mailto:lucasbriandbr@proton.me'>lucasbrianbdr@proton.me</a>&quot;</span><span>,</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Téléphone&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='tel:+33750068971'>+33 7 50 06 89 71</a>&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>
                
                    <p className='px-4 flex gap-4'><span className='text-[#99BB77]'>&quot;Travaux&quot;</span><span>:</span><span className='text-[#C468C9]'>&#123;</span></p>

                        <p className='px-8 flex gap-4'><span className='text-[#99BB77]'>&quot;Bootook&quot;</span><span>:</span><span className='text-[#B26D50]'>&quot;<a className='underline' href='https://www.bootook.com/'>https://www.bootook.com/</a>&quot;</span><span>,</span></p>

                    <p className='px-4 flex gap-4'><span className='text-[#C468C9]'>&#125;</span><span>,</span></p>

                <p className='flex gap-4 text-[#C6C100]'><span>&#125;</span></p>

            </section>

        </div>
    )
}
